# Testing

name: Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deps
        run: |
          pip install sphinx sphinx-rtd theme
      - name: Docs
        run: |
          make docs

  unittests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          make debug
      - name: Run tests
        run: |
          ./build/tests/tests
